// This file is auto-generated from server.ts to hold the pre-seeded datasets for client-side use on Vercel.

export const seedNames = [
    { arabic: "اللَّهُ", transliteration: "আল্লাহ", meaning: "একমাত্র উপাস্য", benefit: "আল্লাহর জিকির অন্তরে প্রশান্তি আনে।" },
    { arabic: "الرَّحْمَنُ", transliteration: "আর-রহমান", meaning: "পরম দয়ালু", benefit: "স্মরণশক্তি ও সচেতনতা বৃদ্ধি পায়।" },
    { arabic: "الرَّحِيمُ", transliteration: "আর-রাহীম", meaning: "অতিশয় দয়ালু", benefit: "শান্তি ও নিরাপত্তা লাভ হয়।" },
    { arabic: "الْمَلِكُ", transliteration: "আল-মালিক", meaning: "সর্বভৌম অধিপতি", benefit: "সম্মান ও মর্যাদা বৃদ্ধি পায়।" },
    { arabic: "الْقُدُّوسُ", transliteration: "আল-কুদুছ", meaning: "অতি পবিত্র", benefit: "অন্তর দুশ্চিন্তা থেকে মুক্ত হয়।" },
    { arabic: "السَّلَامُ", transliteration: "আস-সালাম", meaning: "শান্তি দাতা", benefit: "অসুস্থ ব্যক্তির আরোগ্য লাভে সাহায্য করে।" },
    { arabic: "الْمُؤْمِنُ", transliteration: "আল-মু'মিন", meaning: "নিরাপত্তা দানকারী", benefit: "শত্রুর অনিষ্ট থেকে রক্ষা করে।" },
    { arabic: "الْمُهَيْمِنُ", transliteration: "আল-মুহাইমিন", meaning: "রক্ষণাবেক্ষণকারী", benefit: "অন্তর ও বাহিরের নিরাপত্তা দান করে।" },
    { arabic: "الْعَزِيزُ", transliteration: "আল-আজিজ", meaning: "মহা পরাক্রমশালী", benefit: "অন্যের মুখাপেক্ষী হতে হয় না।" },
    { arabic: "الْجَبَّارُ", transliteration: "আল-জাব্বার", meaning: "মহাপ্রতাপশালী", benefit: "অত্যাচারীর হাত থেকে রক্ষা করে।" },
    { arabic: "الْمُتَكَبِّرُ", transliteration: "আল-মুতাকাব্বির", meaning: "সর্বশ্রেষ্ঠ", benefit: "সাফল্য ও বরকত দান করে।" },
    { arabic: "الْخَالِقُ", transliteration: "আল-খালিক", meaning: "সৃষ্টিকর্তা", benefit: "কঠিন কাজ সহজ করে দেয়।" },
    { arabic: "الْبَارِئُ", transliteration: "আল-বারী", meaning: "উদ্ভাবনকারী", benefit: "রোগ থেকে মুক্তি দান করে।" },
    { arabic: "الْمُصَوِّرُ", transliteration: "আল-মুছউয়্যির", meaning: "আকৃতি দানকারী", benefit: "সন্তান লাভের জন্য দোয়া কবুল হয়।" },
    { arabic: "الْغَفَّارُ", transliteration: "আল-গাফফার", meaning: "মহা ক্ষমাশীল", benefit: "গুনাহ মাফ হয়।" },
    { arabic: "الْقَهَّارُ", transliteration: "আল-কাহহার", meaning: "মহা দমনকারী", benefit: "দুনিয়ার মোহ থেকে মুক্তি দেয়।" },
    { arabic: "الْوَهَّابُ", transliteration: "আল-ওয়াহহাব", meaning: "মহা দাতা", benefit: "দারিদ্র্য দূর করে।" },
    { arabic: "الرَّزَّاقُ", transliteration: "আর-রাজ্জাক", meaning: "রিজিক দাতা", benefit: "রিজিকে বরকত দান করে।" },
    { arabic: "الْفَتَّاحُ", transliteration: "আল-ফাত্তাহ", meaning: "বিজয় দানকারী", benefit: "সাফল্যের পথ খুলে দেয়।" },
    { arabic: "الْعَلِيمُ", transliteration: "আল-আলীম", meaning: "সর্বজ্ঞ", benefit: "জ্ঞান ও প্রজ্ঞা বৃদ্ধি করে।" },
    { arabic: "الْقَابِضُ", transliteration: "আল-কাবিদ", meaning: "সংকোচনকারী", benefit: "ভয়-ভীতি থেকে রক্ষা করে।" },
    { arabic: "الْبَاسِطُ", transliteration: "আল-বাসিত", meaning: "সম্প্রসারণকারী", benefit: "রিজিক ও সুখ বৃদ্ধি করে।" },
    { arabic: "الْخَافِضُ", transliteration: "আল-খাফিদ", meaning: "অবনতকারী", benefit: "শত্রুর অনিষ্ট থেকে রক্ষা করে।" },
    { arabic: "الرَّافِعُ", transliteration: "আর-রাফি", meaning: "উন্নতকারী", benefit: "মর্যাদা ও সম্মান বৃদ্ধি করে।" },
    { arabic: "الْمُعِزُّ", transliteration: "আল-মুইজ্জ", meaning: "সম্মান দানকারী", benefit: "মানুষের চোখে সম্মান বৃদ্ধি পায়।" },
    { arabic: "الْمُذِلُّ", transliteration: "আল-মুজিল্ল", meaning: "অপমানকারী", benefit: "অহংকার থেকে রক্ষা করে।" },
    { arabic: "السَّمِيعُ", transliteration: "আস-সামি", meaning: "সর্বশ্রোতা", benefit: "দোয়া কবুল হওয়ার পথ প্রশস্ত করে।" },
    { arabic: "الْبَصِيرُ", transliteration: "আল-বাছীর", meaning: "সর্বদ্রষ্টা", benefit: "দৃষ্টিশক্তি ও অন্তর্দৃষ্টি বৃদ্ধি পায়।" },
    { arabic: "الْحَكَمُ", transliteration: "আল-হাকাম", meaning: "মহা বিচারক", benefit: "ন্যায়ের পথে অবিচল রাখে।" },
    { arabic: "الْعَدْلُ", transliteration: "আল-আদল", meaning: "মহা ন্যায়পরায়ণ", benefit: "বিচারের সময় সাহায্য করে।" },
    { arabic: "اللَّطِيفُ", transliteration: "আল-লাতীফ", meaning: "পরম সূক্ষ্মদর্শী", benefit: "কঠিন বিপদ থেকে উদ্ধার করে।" },
    { arabic: "الْخَبِيرُ", transliteration: "আল-খাবীর", meaning: "মহা সম্যক অবগত", benefit: "গোপন রহস্য উন্মোচিত হয়।" },
    { arabic: "الْحَلِيمُ", transliteration: "আল-হালীম", meaning: "মহা ধৈর্যশীল", benefit: "রাগ নিয়ন্ত্রণ করতে সাহায্য করে।" },
    { arabic: "الْعَظِيمُ", transliteration: "আল-আযীম", meaning: "মহা মহিমান্বিত", benefit: "ভয় ও আতঙ্ক দূর করে।" },
    { arabic: "الْغَفُورُ", transliteration: "আল-গাফুর", meaning: "মহা ক্ষমাশীল", benefit: "মানসিক প্রশান্তি দান করে।" },
    { arabic: "الشَّكُورُ", transliteration: "আশ-শাকুর", meaning: "মহা গুণগ্রাহী", benefit: "নেয়ামত বৃদ্ধি পায়।" },
    { arabic: "الْعَلِيُّ", transliteration: "আল-আলী", meaning: "মহা উন্নত", benefit: "উচ্চ মর্যাদা দান করে।" },
    { arabic: "الْكَبِيرُ", transliteration: "আল-কাবীর", meaning: "মহা বড়", benefit: "কাজে বরকত দান করে।" },
    { arabic: "الْحَفِيظُ", transliteration: "আল-হাফীয", meaning: "মহা রক্ষক", benefit: "বিপদ-আপদ থেকে রক্ষা করে।" },
    { arabic: "الْمُقِيتُ", transliteration: "আল-মুকীত", meaning: "মহা শক্তিদাতা", benefit: "ক্ষুধা ও অভাব থেকে মুক্তি দেয়।" },
    { arabic: "الْحَسِيبُ", transliteration: "আল-হাসীব", meaning: "মহা হিসাব গ্রহণকারী", benefit: "শত্রুর ভয় থেকে মুক্তি দেয়।" },
    { arabic: "الْجَلِيلُ", transliteration: "আল-জালীল", meaning: "মহা প্রতাপশালী", benefit: "ব্যক্তিত্ব ও গাম্ভীর্য বৃদ্ধি করে।" },
    { arabic: "الْكَرِيمُ", transliteration: "আল-কারীম", meaning: "মহা দয়ালু", benefit: "দুনিয়া ও আখেরাতে সম্মান দান করে।" },
    { arabic: "الرَّقِيبُ", transliteration: "আর-রাকীব", meaning: "মহা তত্ত্বাবধায়ক", benefit: "পরিবার ও সম্পদের নিরাপত্তা দেয়।" },
    { arabic: "الْمُجِيبُ", transliteration: "আল-মজীব", meaning: "মহা দোয়া কবুলকারী", benefit: "দোয়া দ্রুত কবুল হয়।" },
    { arabic: "الْوَاسِعُ", transliteration: "আল-ওয়াসি", meaning: "মহা অসীম", benefit: "রিজিকের অভাব দূর করে।" },
    { arabic: "الْحَكِيمُ", transliteration: "আল-হাকীম", meaning: "মহা প্রজ্ঞাময়", benefit: "কাজে প্রজ্ঞা ও কৌশল দান করে।" },
    { arabic: "الْوَدُودُ", transliteration: "আল-ওয়াদুদ", meaning: "মহা প্রেমময়", benefit: "মানুষের মধ্যে ভালোবাসা সৃষ্টি করে।" },
    { arabic: "الْمَجِيدُ", transliteration: "আল-মাজীদ", meaning: "মহা গৌরবময়", benefit: "যশ ও খ্যাতি বৃদ্ধি করে।" },
    { arabic: "الْبَاعِثُ", transliteration: "আল-বাইস", meaning: "মহা পুনরুত্থানকারী", benefit: "পরকালের ভয় অন্তরে জাগ্রত করে।" },
    { arabic: "الشَّهِيدُ", transliteration: "আশ-শাহীদ", meaning: "মহা সাক্ষী", benefit: "সন্তানকে অনুগত করে।" },
    { arabic: "الْحَقُّ", transliteration: "আল-হাক্ক", meaning: "মহা সত্য", benefit: "হারানো জিনিস ফিরে পেতে সাহায্য করে।" },
    { arabic: "الْوَكِيلُ", transliteration: "আল-ওয়াকীল", meaning: "মহা কর্মবিধায়ক", benefit: "বিপদে আল্লাহর ওপর ভরসা বাড়ায়।" },
    { arabic: "الْقَوِيُّ", transliteration: "আল-কাউয়্যি", meaning: "মহা শক্তিশালী", benefit: "শারীরিক ও মানসিক শক্তি দান করে।" },
    { arabic: "الْمَتِينُ", transliteration: "আল-মতীন", meaning: "মহা দৃঢ়", benefit: "কঠিন কাজে দৃঢ়তা দান করে।" },
    { arabic: "الْوَلِيُّ", transliteration: "আল-ওয়ালীয়", meaning: "মহা বন্ধু", benefit: "আল্লাহর নৈকট্য দান করে।" },
    { arabic: "الْحَمِيدُ", transliteration: "আল-হামীদ", meaning: "মহা প্রশংসিত", benefit: "চরিত্র সুন্দর করে।" },
    { arabic: "الْمُحْصِي", transliteration: "আল-মুহছী", meaning: "মহা হিসাব রক্ষক", benefit: "হিসাব নিকাশ সহজ করে।" },
    { arabic: "الْمُبْدِئُ", transliteration: "আল-মুবদী", meaning: "মহা আদি স্রষ্টা", benefit: "কাজে সফলতা দান করে।" },
    { arabic: "الْمُعِيدُ", transliteration: "আল-মুঈদ", meaning: "মহা প্রত্যাবর্তনকারী", benefit: "ভুলে যাওয়া জিনিস মনে করিয়ে দেয়।" },
    { arabic: "الْمُحْيِي", transliteration: "আল-মুহয়ী", meaning: "মহা জীবনদাতা", benefit: "কঠিন রোগ থেকে মুক্তি দেয়।" },
    { arabic: "الْمُمِيتُ", transliteration: "আল-মুমীত", meaning: "মহা মৃত্যু দাতা", benefit: "শত্রুর অনিষ্ট থেকে রক্ষা করে।" },
    { arabic: "الْحَيُّ", transliteration: "আল-হাইয়্য", meaning: "মহা চিরঞ্জীব", benefit: "দীর্ঘায়ু ও সুস্বাস্থ্য দান করে।" },
    { arabic: "الْقَيُّومُ", transliteration: "আল-কাইয়্যুম", meaning: "মহা স্বয়ংসম্পূর্ণ", benefit: "অলসতা দূর করে।" },
    { arabic: "الْوَاجِدُ", transliteration: "আল-ওয়াজিদ", meaning: "মহা প্রাপক", benefit: "মনের আশা পূরণ করে।" },
    { arabic: "الْمَاجِدُ", transliteration: "আল-মাজিদ", meaning: "মহা মহিমান্বিত", benefit: "অন্তর আলোকিত করে।" },
    { arabic: "الْوَاحِدُ", transliteration: "আল-ওয়াহিদ", meaning: "মহা এক", benefit: "একাকীত্বের ভয় দূর করে।" },
    { arabic: "الْأَحَدُ", transliteration: "আল-আহাদ", meaning: "মহা অদ্বিতীয়", benefit: "ইমান মজবুত করে।" },
    { arabic: "الصَّمَدُ", transliteration: "আছ-ছামাদ", meaning: "মহা অমুখাপেক্ষী", benefit: "কারো মুখাপেক্ষী হতে হয় না।" },
    { arabic: "الْقَادِرُ", transliteration: "আল-কাদির", meaning: "মহা ক্ষমতাধর", benefit: "অসাধ্য সাধন করতে সাহায্য করে।" },
    { arabic: "الْمُقْتَدِرُ", transliteration: "আল-মুকতাদির", meaning: "মহা প্রবল শক্তিশালী", benefit: "বিপদে ধৈর্য ধারণ করতে সাহায্য করে।" },
    { arabic: "الْمُقَدِّمُ", transliteration: "আল-মুকাদ্দিম", meaning: "মহা অগ্রগামীকারী", benefit: "বিপদে সাহস দান করে।" },
    { arabic: "الْمُؤَخِّرُ", transliteration: "আল-মুয়াখখির", meaning: "মহা বিলম্বকারী", benefit: "তওবা কবুল হতে সাহায্য করে।" },
    { arabic: "الْأَوَّلُ", transliteration: "আল-আউয়াল", meaning: "মহা আদি", benefit: "কাজে বরকত দান করে।" },
    { arabic: "الْآخِرُ", transliteration: "আল-আখির", meaning: "মহা অন্ত", benefit: "শেষ পরিণাম ভালো করে।" },
    { arabic: "الظَّاهِرُ", transliteration: "আজ-জাহির", meaning: "মহা প্রকাশ্য", benefit: "দৃষ্টিশক্তি প্রখর করে।" },
    { arabic: "الْبَاطِنُ", transliteration: "আল-বাতিন", meaning: "মহা গোপন", benefit: "অন্তরের নূর বৃদ্ধি করে।" },
    { arabic: "الْوَالِي", transliteration: "আল-ওয়ালী", meaning: "মহা অভিভাবক", benefit: "বিপদ থেকে রক্ষা করে।" },
    { arabic: "الْمُتَعَالِي", transliteration: "আল-মুতালী", meaning: "মহা সর্বোচ্চ", benefit: "মর্যাদা বৃদ্ধি করে।" },
    { arabic: "الْبَرُّ", transliteration: "আল-বারর", meaning: "মহা কল্যাণদাতা", benefit: "সন্তানকে নেককার করে।" },
    { arabic: "التَّوَّابُ", transliteration: "আত-তাওয়াব", meaning: "মহা তওবা কবুলকারী", benefit: "তওবা কবুল হয়।" },
    { arabic: "الْمُنْتَقِمُ", transliteration: "আল-মুনতাকিম", meaning: "মহা প্রতিশোধ গ্রহণকারী", benefit: "অত্যাচারীর হাত থেকে রক্ষা করে।" },
    { arabic: "الْعَفُوُّ", transliteration: "আল-আফুউ", meaning: "মহা ক্ষমাশীল", benefit: "গুনাহ মাফ হয়।" },
    { arabic: "الرَّؤُوفُ", transliteration: "আর-রউফ", meaning: "মহা দয়ালু", benefit: "সবার ভালোবাসা পাওয়া যায়।" },
    { arabic: "مَالِكُ الْمُلْكِ", transliteration: "মালিকুল মুলক", meaning: "মহা সার্বভৌম অধিপতি", benefit: "রিজিক ও সম্মানে বরকত হয়।" },
    { arabic: "ذُو الْجَلَالِ وَالْإِكْرَامِ", transliteration: "যুল জালালি ওয়াল ইকরম", meaning: "মহা মহিমাময় ও মহানুভব", benefit: "দোয়া কবুল হয়।" },
    { arabic: "الْمُقْسِطُ", transliteration: "আল-মুকসিত", meaning: "মহা ন্যায়পরায়ণ", benefit: "শয়তানের ওয়াসওয়াসা থেকে রক্ষা করে।" },
    { arabic: "الْجَامِعُ", transliteration: "আল-জামি", meaning: "মহা একত্রকারী", benefit: "হারানো জিনিস ফিরে পাওয়া যায়।" },
    { arabic: "الْغَنِيُّ", transliteration: "আল-গানিই", meaning: "মহা ধনী", benefit: "অভাব দূর হয়।" },
    { arabic: "الْمُغْنِي", transliteration: "আল-মুগনিই", meaning: "মহা অভাবমোচনকারী", benefit: "স্বাবলম্বী হওয়া যায়।" },
    { arabic: "الْمَانِعُ", transliteration: "আল-মানি", meaning: "মহা প্রতিরোধকারী", benefit: "বিপদ থেকে রক্ষা করে।" },
    { arabic: "الضَّارُّ", transliteration: "আদ-দারর", meaning: "মহা অনিষ্টকারী", benefit: "বিপদ থেকে শিক্ষা দেয়।" },
    { arabic: "النَّافِعُ", transliteration: "আন-নাফি", meaning: "মহা কল্যাণকারী", benefit: "কাজে সফলতা আসে।" },
    { arabic: "النُّورُ", transliteration: "আন-নূর", meaning: "মহা জ্যোতি", benefit: "অন্তর আলোকিত হয়।" },
    { arabic: "الْهَادِي", transliteration: "আল-হাদী", meaning: "মহা পথপ্রদর্শক", benefit: "সঠিক পথ দেখায়।" },
    { arabic: "الْبَدِيعُ", transliteration: "আল-বাদী", meaning: "মহা অপূর্ব স্রষ্টা", benefit: "দুশ্চিন্তা দূর হয়।" },
    { arabic: "الْبَاقِي", transliteration: "আল-বাকী", meaning: "মহা চিরস্থায়ী", benefit: "নেক আমল কবুল হয়।" },
    { arabic: "الْوَارِثُ", transliteration: "আল-ওয়ারিস", meaning: "মহা উত্তরাধিকারী", benefit: "দীর্ঘায়ু লাভ হয়।" },
    { arabic: "الرَّشِيدُ", transliteration: "আর-রাশীদ", meaning: "মহা সত্যপথ প্রদর্শক", benefit: "কাজে সঠিক সিদ্ধান্ত নেওয়া যায়।" },
    { arabic: "الصَّبُورُ", transliteration: "আছ-ছাবুর", meaning: "মহা ধৈর্যশীল", benefit: "বিপদে ধৈর্য ধরার শক্তি পায়।" },
  ];

export const seedResources = [
    { title: 'রমজান প্রস্তুতি গাইড', category: 'রমজান', url: 'https://example.com/ramadan-guide.pdf' },
    { title: 'দৈনিক সকালের জিকির', category: 'দোয়া', url: 'https://example.com/adhkar.pdf' },
    { title: 'যাকাত সম্পর্কে ধারণা', category: 'ফিকহ', url: 'https://example.com/zakat.pdf' },
    { title: 'রাসূলুল্লাহ (সা.)-এর চরিত্র', category: 'নিবন্ধ', url: 'https://example.com/akhlaq.pdf' },
  ];

export const seedDailyContent = [
  { id: 1, type: 'ayah', content: 'নিশ্চয় কষ্টের সাথেই স্বস্তি রয়েছে।', reference: 'আল-কুরআন ৯৪:৬', active: 1 },
  { id: 2, type: 'hadith', content: 'তোমাদের মধ্যে সেই ব্যক্তিই সর্বোত্তম যে কুরআন শেখে এবং অন্যকে শেখায়।', reference: 'সহীহ বুখারী', active: 0 }
];

export const seedTasbihPresets = [
  { id: 1, name: 'সুবহানাল্লাহ', target: 33 },
  { id: 2, name: 'আলহামদুলিল্লাহ', target: 33 },
  { id: 3, name: 'আল্লাহু আকবার', target: 34 }
];
